CREATE TABLE dcms_child (ID INTEGER AUTO_INCREMENT NOT NULL, affliation INTEGER, dob DATE, first_name VARCHAR(255), last_name VARCHAR(255), middle_name VARCHAR(255), note VARCHAR(255), phone VARCHAR(255), slibling_id INTEGER, active_enrollment INTEGER, PRIMARY KEY (ID))
CREATE TABLE dcms_teacher (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), fri_time VARCHAR(255), mon_time VARCHAR(255), thu_time VARCHAR(255), tue_time VARCHAR(255), wed_time VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE dcms_waitinglist (ID INTEGER AUTO_INCREMENT NOT NULL, application_date DATE, attending_mode VARCHAR(255), customized_sequence INTEGER, desire_date DATE, expect_grade INTEGER, note VARCHAR(255), offered_date DATE, status VARCHAR(255), child INTEGER, PRIMARY KEY (ID))
CREATE TABLE dcms_enrollment (ID INTEGER AUTO_INCREMENT NOT NULL, accept_date DATE, attending_mode VARCHAR(255), contract_from_date DATE, contract_to_date DATE, contract_from DATE, STATUS INTEGER, TERM VARCHAR(255), fri_time VARCHAR(255), mon_time VARCHAR(255), thu_time VARCHAR(255), tue_time VARCHAR(255), wed_time VARCHAR(255), child_id INTEGER, classroom_id INTEGER, PRIMARY KEY (ID))
CREATE TABLE dcms_classroom (ID INTEGER AUTO_INCREMENT NOT NULL, capacity INTEGER, grade INTEGER, name VARCHAR(255), student_num INTEGER, PRIMARY KEY (ID))
CREATE TABLE dcms_event_log (ID INTEGER AUTO_INCREMENT NOT NULL, EVENT VARCHAR(255), EVENTDATE DATETIME, NOTE VARCHAR(255), child_id INTEGER, PRIMARY KEY (ID))
CREATE TABLE dcms_child_contact (ADDRESS VARCHAR(255), EMAIL VARCHAR(255), first_name VARCHAR(255), last_name VARCHAR(255), middle_name VARCHAR(255), NOTE VARCHAR(255), PHONE1 VARCHAR(255), PHONE2 VARCHAR(255), role VARCHAR(255), status VARCHAR(255), child_id INTEGER)
CREATE TABLE dcms_classroom_teacher (teacher_id INTEGER NOT NULL, classroom_id INTEGER NOT NULL, PRIMARY KEY (teacher_id, classroom_id))
ALTER TABLE dcms_child ADD CONSTRAINT FK_dcms_child_active_enrollment FOREIGN KEY (active_enrollment) REFERENCES dcms_enrollment (ID)
ALTER TABLE dcms_waitinglist ADD CONSTRAINT FK_dcms_waitinglist_child FOREIGN KEY (child) REFERENCES dcms_child (ID)
ALTER TABLE dcms_enrollment ADD CONSTRAINT FK_dcms_enrollment_classroom_id FOREIGN KEY (classroom_id) REFERENCES dcms_classroom (ID)
ALTER TABLE dcms_enrollment ADD CONSTRAINT FK_dcms_enrollment_child_id FOREIGN KEY (child_id) REFERENCES dcms_child (ID)
ALTER TABLE dcms_event_log ADD CONSTRAINT FK_dcms_event_log_child_id FOREIGN KEY (child_id) REFERENCES dcms_child (ID)
ALTER TABLE dcms_child_contact ADD CONSTRAINT FK_dcms_child_contact_child_id FOREIGN KEY (child_id) REFERENCES dcms_child (ID)
ALTER TABLE dcms_classroom_teacher ADD CONSTRAINT FK_dcms_classroom_teacher_classroom_id FOREIGN KEY (classroom_id) REFERENCES dcms_classroom (ID)
ALTER TABLE dcms_classroom_teacher ADD CONSTRAINT FK_dcms_classroom_teacher_teacher_id FOREIGN KEY (teacher_id) REFERENCES dcms_teacher (ID)
